# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "5741f8c8b9d42b85bca373730147a177d1b2147ea9a1600a9958985dc18560a0"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "06c3f3593e587f2d4e3f4b1f0643c07d4bb684d51356eec4e0cb42973cc3a16b"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "17acfc149541dc65e7b5bf7239ca340a0183a06ca3b255c41b26e366cf46f1d7"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "edd83838372cead9f2cd6a4b850fc3d2f57ffd77d1d61d30831a79de8c4c02ed"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flow"
  desc "A complete task manager for Claude Code — and the working memory layer that turns every session from a brilliant new hire into the engineer on your team."
  homepage "https://github.com/aabhas-sao/flow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"

  # No zap stanza required

  caveats <<~EOS
    After installation, you must run:
      flow init
    to set up the SQLite database and wire flow into Claude Code.
  EOS
end
