# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "59413f036ee32cc9c02b0813580245ca01bb1faafebc69339cff362673895a21"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d4041310d41f44d53301fb23cb1db8a7127b4d3c2606c1cf9ebb187958d9474f"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "404dfb677bd5f8a5cde7b4b6fb9b9690eb0d9ddeb65f42a46f48b659442a6c1d"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3b77660bdb8b048f5de16a5a217f146b81cbb888e75f5be9e1f0604a6d4d33f"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flow"
  desc "A complete task manager for Claude Code — and the working memory layer that turns every session from a brilliant new hire into the engineer on your team."
  homepage "https://github.com/aabhas-sao/flow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"

  # No zap stanza required

  caveats <<~EOS
    After installation, you must run:
      flow init
    to set up the SQLite database and wire flow into Claude Code.
  EOS
end
