# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "0814d834a2d958057c72140e7aa3bd6cca484c3ab2689d7fd04f424287368d2f"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "101d28f95c76d819edbbfe49806a7599d447cc42515270d31181334348e84380"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e510f4f1d8435b4f579a48164bb3dd3fc1bf4affc8948645f5af01e6b9b6ab55"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b58172256c469ada535653765d7bd9350428933bdbc65816e3792b1e7cfbb652"
      url "https://github.com/aabhas-sao/flow/releases/download/v#{version}/flow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flow"
  desc "A complete task manager for Claude Code — and the working memory layer that turns every session from a brilliant new hire into the engineer on your team."
  homepage "https://github.com/aabhas-sao/flow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/flow"], sudo: true
  end

  # No zap stanza required

  caveats <<~EOS
    After installation, you must run:
      flow init
    to set up the SQLite database and wire flow into Claude Code.
  EOS
end
