# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "A complete task manager for Claude Code — and the working memory layer that turns every session from a brilliant new hire into the engineer on your team."
  homepage "https://github.com/aabhas-sao/flow"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aabhas-sao/flow/releases/download/v0.1.1/flow_0.1.1_darwin_amd64.tar.gz"
      sha256 "30ad6690e08e28c03baf5b2e64a03e8f21f495429b94b9292b2a7c31deff0a33"

      define_method(:install) do
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aabhas-sao/flow/releases/download/v0.1.1/flow_0.1.1_darwin_arm64.tar.gz"
      sha256 "7a029ccf46e9990c1454f44bb4f5d2990981ee51048dfcc05dca074a08cf1f92"

      define_method(:install) do
        bin.install "flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aabhas-sao/flow/releases/download/v0.1.1/flow_0.1.1_linux_amd64.tar.gz"
      sha256 "6ab6e8caa4aec1fa2b74cfefda4367ea8c5677787c30c23f8d6b8b0fce9a7e5c"
      define_method(:install) do
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aabhas-sao/flow/releases/download/v0.1.1/flow_0.1.1_linux_arm64.tar.gz"
      sha256 "8dfb1a68ce83c5257f215405fc0105c75d9c60353523094f0beb1e85b5237fae"
      define_method(:install) do
        bin.install "flow"
      end
    end
  end

  def caveats
    <<~EOS
      After installation, you must run:
        flow init
      to set up the SQLite database and wire flow into Claude Code.
    EOS
  end

  test do
    system "#{bin}/flow --version"
  end
end
